version: '3.8'

services:
  askmi_app:
    depends_on:
      - askmi_database
      - askmi_redis
    build: .
    restart: always
    ports:
      - $APP_PORT:$APP_PORT
    networks:
      - askmi_network
    env_file: ./.env
    environment:
      - REDIS_URI=redis://ask_redis:6379
    volumes:
      - .:/app
      - node_modules:/app/node_modules

  askmi_database:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    networks:
      - askmi_network
    volumes:
      - data:/data/db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
  askmi_redis:
    image: redis:6.2.5-alpine
    restart: always
    ports:
      - '6379:6379'
    networks:
      - askmi_network
    volumes:
      - redis_data:/data

networks:
  askmi_network:

volumes:
  data:
  redis_data:
  node_modules:
